name: Build, lint and test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    uses: cloudscape-design/actions/.github/workflows/build-lint-test.yml@main
    secrets: inherit
    with:
      artifact-path: build/allure-report
      artifact-name: allure-report
  deploy:
    needs: build
    uses: cloudscape-design/actions/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      artifact-name: allure-report
      deployment-path: build/allure-report
